language: node_js
node_js:
  - "stable"
before_script:
  - npm install gulp
script: gulp
cache:
  directories:
    - node_modules
before_cache:
  - rm -f node_modules/web-component-tester/package.json